### ISSUE TITLE
Package request: CFSSL: Cloudflare's PKI and TLS toolkit

### ISSUE THREAD

**Issue by fred-vogt** [lambci/yumda#11]
Possible use cases:
* provision kubernetes ROOT CAs from a lambda secrets manager rotation function, generate CSRs, etc...

Specifically: `cfssl, cfssljson, mkbundle` are handy tools to have available in an Amazon Linux 2 runtime
* https://github.com/cloudflare/cfssl

The Makefile as a target for RPMs:
* [github.com/cloudflare/cfssl/Makefile](https://github.com/cloudflare/cfssl/blob/2916a1fa6bf37b6d7a672a9be7e734871e08039c/Makefile#L92)

Out of date 1.2 RPM:
*I https://github.com/hnakamur/cfssl-rpm/blob/master/SPECS/cfssl.spec

**Comment by mhart** [comment]
Done 👍  Lemme know if it works for you

**Comment by fred-vogt** [comment]
@mhart - confirmed.  Thanks.
