### ISSUE TITLE
golang package suggestion 🙏

### ISSUE THREAD

**Issue by brianleroux** [lambci/yumda#13]
is there cocktail delivery in nyc and do you accept bribes? 🍸

**Comment by mhart** [comment]
Can you expand a bit? The official way to install Go for Linux is a one-line curl/tar command – not even sure there are official rpms?

**Comment by mhart** [comment]
Ah, so there are rpms for Amazon Linux, but they include the kitchen sink...

```
Total download size: 183 M
Installed size: 626 M
``` 

You *sure* you don't wanna just curl/tar? 😉

**Comment by brianleroux** [comment]
oooof argh ya guess so. I have a janky layer rig that predates nicer SAR dist stuff and uses yumda (ty again for this project).

another branch in my janky rig is fiiiiiine 👍
