### ISSUE TITLE
Add epel package eccodes (Amazon Linux 2)

### ISSUE THREAD

**Issue by iamed2** [lambci/yumda#5]
It would really help us if eccodes-devel, eccodes, and eccodes-data were available. All are available from the `epel` repo installed with `amazon-linux-extras`. 

Thanks for the excellent Lambda environment!

**Comment by mhart** [comment]
Will look into it, thanks for the request! Out of interest, why the need for the devel package `eccodes-devel`? What does it provide that you need on Lambda?

**Comment by iamed2** [comment]
`eccodes-devel` provides the `libeccodes.so` file while `eccodes` only provides the versioned library (currently `libeccodes.so.0.1`). But more importantly, `eccodes-python` uses the header files to provide the CFFI interface: https://github.com/ecmwf/eccodes-python#fast-bindings

**Comment by mhart** [comment]
But `libeccodes.so` would only be used at build-time, right? Are you doing the compilation on Lambda?

**Comment by iamed2** [comment]
We're building in the `lambci/lambda:build-python*` images, yeah

**Comment by mhart** [comment]
Ah, in that case you don't need any packages to be built for Lambda – they should install just fine in the `build-python*` environments using `yum` as you normally would (because you have root access, etc).

`yumda` is intended for when you need packages in your Lambda *runtime*

**Comment by iamed2** [comment]
Oh, we do need the shared library at runtime as well. We build our lambdas in a lambda environment, pull everything out into a zip (including libeccodes.so.0.1 and the eccodes-data files) and then push that. But we don't need to _install_ it at runtime if that's what you're saying.

EDIT: I realize now you may mean for building a custom lambda runtime? Either way, the question below should still resolve things.

So should an eccodes shared library installed from epel in the `lambci/lambda:build-python*` environment work in both Lambda and the `lambci/lambda:python*` environments, as far as this project is concerned?

**Comment by mhart** [comment]
Sorry, I should've been more specific in that I'm only talking about the `devel` package. That should only be needed at build time (in which case, you don't need it in `yumda`). I'll look into building the others 👍

**Comment by iamed2** [comment]
Okay, right, thanks!

**Comment by mhart** [comment]
Just added `eccodes` and `eccodes-data` – let me know if that works for you!

**Comment by iamed2** [comment]
Thank you!
